Fix spline color term apply code so that it returns the target flux.
lsst-dm/the_monster pull request #7
Opened 2023-09-05 21:03 UTC by erykoff

2023-09-06 14:04 UTC, psferguson requested changes
I also think you will need to update the qa plots to deal with the new format of the apply output

I think this is the only time that happens: https://github.com/lsst-dm/the_monster/blob/1cbe00db062e69233c546841f3a7c03bcfa7b3db/python/lsst/the/monster/measure_colorterms.py#L198

2023-09-06 14:04 UTC, psferguson commented on python/lsst/the/monster/splinecolorterms.py
> +        target = self.spline.interpolate(mag_color) * source_flux
are you sure target = model * source_flux 
based off the cost function https://github.com/lsst-dm/the_monster/blob/08b3df7e1f1a56311da2aa0d2f48d0b714a39770/python/lsst/the/monster/splinecolorterms.py#L206

I would have assumed target_flux = source_flux / model

2023-09-06 15:49 UTC, erykoff commented
You're right, this was backwards and mixed up.  I messed up the application, as well as the flux offset.  This has been fixed, but I need to remeasure the color terms.  Those will be pushed on this PR in a few minutes.

2023-09-07 15:42 UTC, psferguson approved these changes
This looks good, much easier for me to follow along the details of applying the model.

And the unit test looks more robust

2023-09-07 16:49 UTC, merged